/**
 * ============================================================================
 * FILE: /app/(client)/client/reports/page.tsx
 * ============================================================================
 *
 * WHAT THIS FILE IS:
 *   Client portal — Reports page. Displays a read-only list of reports
 *   generated by the advisor for this client. Clients can view and download
 *   published reports but cannot create, edit, or delete them.
 *
 * DATA SOURCE:
 *   `useReports` hook from `@/lib/hooks/crud/use-reports`
 *   Fetches reports from the GraphQL API (same as the advisor page).
 *   The resolver enforces org-scoping, so clients only see their own org's reports.
 *
 * DB ENUMS:
 *   reportType: portfolio_summary | asset_allocation | performance |
 *               tax_summary | compliance | client_statement | custom
 *   status:     draft | published | archived
 *
 * RELATED FILES:
 *   - app/(dashboard)/app/reports/page.tsx — advisor-facing reports (full CRUD)
 *   - lib/hooks/crud/use-reports.ts        — data hooks
 */

"use client"

import * as React from "react"
import { useSpring, animated, config } from "@react-spring/web"
import { format } from "date-fns"
import {
  Download,
  Eye,
  FileText,
  BarChart3,
  Calendar,
  CheckCircle2,
  Clock,
  Archive,
  Shield,
  Receipt,
  FileSpreadsheet,
  TrendingUp,
  PieChart,
  Users,
} from "lucide-react"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"
import { useReducedMotion } from "@/lib/hooks/use-reduced-motion"
import { useReports } from "@/lib/hooks/crud/use-reports"

// ─── DISPLAY CONFIG ─────────────────────────────────────────────────────────
//
// Maps DB enum values to display labels, icons, and colors.

const reportTypeConfig = {
  portfolio_summary: { label: "Portfolio Summary", icon: BarChart3, color: "text-tiffany-500", bg: "bg-tiffany-500/10" },
  asset_allocation: { label: "Asset Allocation", icon: PieChart, color: "text-cyan-400", bg: "bg-cyan-400/10" },
  performance: { label: "Performance", icon: TrendingUp, color: "text-emerald-400", bg: "bg-emerald-400/10" },
  tax_summary: { label: "Tax Summary", icon: Receipt, color: "text-amber-400", bg: "bg-amber-400/10" },
  compliance: { label: "Compliance", icon: Shield, color: "text-blue-400", bg: "bg-blue-400/10" },
  client_statement: { label: "Client Statement", icon: Users, color: "text-rose-400", bg: "bg-rose-400/10" },
  custom: { label: "Custom", icon: FileSpreadsheet, color: "text-purple-400", bg: "bg-purple-400/10" },
}

const statusConfig = {
  draft: { label: "Draft", icon: Clock, color: "text-amber-400" },
  published: { label: "Published", icon: CheckCircle2, color: "text-emerald-400" },
  archived: { label: "Archived", icon: Archive, color: "text-zinc-500" },
}

// ─── PAGE COMPONENT ─────────────────────────────────────────────────────────

export default function ClientReportsPage() {
  const reducedMotion = useReducedMotion()
  const { reports, isLoading } = useReports()

  const spring = useSpring({
    from: { opacity: 0, transform: "translateY(20px)" },
    to: { opacity: 1, transform: "translateY(0px)" },
    config: config.gentle,
    immediate: reducedMotion,
  })

  // Clients only see published reports
  const publishedReports = reports.filter((r) => r.status === "published")

  return (
    <animated.div style={spring} className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-zinc-100">My Reports</h1>
        <p className="text-zinc-400 mt-1">
          View and download your portfolio reports
        </p>
      </div>

      {/* Quick Download Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {Object.entries(reportTypeConfig)
          .slice(0, 4)
          .map(([key, cfg]) => {
            const Icon = cfg.icon
            return (
          <Card key={key} className="cursor-pointer hover:border-zinc-700 transition-colors">
            <CardContent className="p-4 flex items-center gap-3">
              <div className={cn("p-2 rounded-lg", cfg.bg)}>
                <Icon className={cn("h-5 w-5", cfg.color)} />
              </div>
              <div>
                <p className="font-medium text-zinc-100">{cfg.label}</p>
                <p className="text-xs text-zinc-500">Latest Report</p>
              </div>
            </CardContent>
          </Card>
            )
        })}
      </div>

      {/* Recent Reports */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Recent Reports</CardTitle>
          <CardDescription>Your generated reports</CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <p className="text-center text-zinc-500 py-8">Loading reports…</p>
          ) : publishedReports.length === 0 ? (
            <div className="text-center text-zinc-500 py-8">
              <FileText className="h-8 w-8 mx-auto mb-2 opacity-50" />
              <p>No reports available yet.</p>
            </div>
          ) : (
            <div className="space-y-4">
              {publishedReports.map((report) => {
                const typeConfig = reportTypeConfig[report.reportType]
                const status = statusConfig[report.status]

                return (
                  <div
                    key={report.id}
                    className="flex items-center justify-between p-4 rounded-lg border border-zinc-800 hover:border-zinc-700 transition-colors"
                  >
                    <div className="flex items-center gap-4">
                      <div className={cn("p-2 rounded-lg", typeConfig.bg)}>
                        <typeConfig.icon className={cn("h-5 w-5", typeConfig.color)} />
                      </div>
                      <div>
                        <p className="font-medium text-zinc-100">{report.name}</p>
                        <div className="flex items-center gap-3 mt-1 text-sm text-zinc-500">
                          <span className="flex items-center gap-1">
                            <Calendar className="h-3 w-3" />
                            {typeConfig.label}
                          </span>
                          <span>
                            Created {format(new Date(report.createdAt), "MMM d, yyyy")}
                          </span>
                        </div>
                      </div>
                    </div>

                    <div className="flex items-center gap-3">
                      <div className="flex items-center gap-1.5">
                        <status.icon className={cn("h-4 w-4", status.color)} />
                        <span className={cn("text-sm", status.color)}>{status.label}</span>
                      </div>

                      <div className="flex items-center gap-2">
                        <Button variant="outline" size="sm">
                          <Eye className="h-4 w-4 mr-1" />
                          View
                        </Button>
                        <Button variant="outline" size="sm">
                          <Download className="h-4 w-4 mr-1" />
                          Download
                        </Button>
                      </div>
                    </div>
                  </div>
                )
              })}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Request Report */}
      <Card className="border-tiffany-500/20 bg-tiffany-500/5">
        <CardContent className="p-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="font-medium text-zinc-100">Need a custom report?</p>
              <p className="text-sm text-zinc-400 mt-1">
                Contact your advisor to request a custom analysis or report.
              </p>
            </div>
            <Button>Request Report</Button>
          </div>
        </CardContent>
      </Card>
    </animated.div>
  )
}
